2022-12-30 07:50:54,126 | INFO | You launched the model iteration Hippolyte_reconquest
2022-12-30 07:50:54,126 | INFO | You have chosen the model cnn Hippolyte_reconquest
2022-12-30 08:10:54,506 | INFO | Epoch [1/10], Loss: 0.51. Accuracy of the network on the test set: 73.55 %
2022-12-30 08:32:33,056 | INFO | Epoch [2/10], Loss: 0.506. Accuracy of the network on the test set: 73.905 %
2022-12-30 08:59:02,824 | INFO | Epoch [3/10], Loss: 0.503. Accuracy of the network on the test set: 74.159 %
2022-12-30 09:31:52,544 | INFO | Epoch [4/10], Loss: 0.506. Accuracy of the network on the test set: 74.45 %
2022-12-30 10:16:22,406 | INFO | Epoch [5/10], Loss: 0.514. Accuracy of the network on the test set: 74.35 %
2022-12-30 11:03:57,339 | INFO | Epoch [6/10], Loss: 0.532. Accuracy of the network on the test set: 75.886 %
2022-12-30 11:48:31,573 | INFO | Epoch [7/10], Loss: 0.502. Accuracy of the network on the test set: 76.45 %
2022-12-30 12:39:13,027 | INFO | Epoch [8/10], Loss: 0.507. Accuracy of the network on the test set: 76.659 %
2022-12-30 13:27:48,164 | INFO | Epoch [9/10], Loss: 0.494. Accuracy of the network on the test set: 77.813 %
2022-12-30 14:14:26,107 | INFO | Epoch [10/10], Loss: 0.516. Accuracy of the network on the test set: 77.077 %
2022-12-30 14:16:24,813 | WARNING | The model has finished training Hippolyte_reconquest
2023-01-01 09:24:07,489 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 09:24:07,490 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 09:24:34,199 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 09:24:34,200 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 09:45:16,412 | INFO | Epoch [1/10], Loss: 0.689. Accuracy of the network on the test set: 59.503 %
2023-01-01 09:55:19,773 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 09:55:19,773 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 10:10:38,657 | INFO | Epoch [1/10], Loss: 0.692. Accuracy of the network on the test set: 59.513 %
2023-01-01 10:26:01,444 | INFO | Epoch [2/10], Loss: 0.692. Accuracy of the network on the test set: 59.513 %
2023-01-01 10:26:01,478 | WARNING | The model training has stopped at epoch 2 due to the early stopping criterion
2023-01-01 10:41:08,120 | WARNING | The model has finished training Hippolyte_reconquest
2023-01-01 10:52:39,922 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 10:52:39,922 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 10:53:03,836 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 10:53:03,837 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 10:53:30,293 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 10:53:30,293 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 11:11:11,132 | INFO | Epoch [1/10], Loss: 0.451. Accuracy of the network on the test set: 59.526 %
2023-01-01 11:27:44,948 | INFO | Epoch [2/10], Loss: 0.532. Accuracy of the network on the test set: 72.359 %
2023-01-01 11:44:07,910 | INFO | Epoch [3/10], Loss: 0.508. Accuracy of the network on the test set: 72.047 %
2023-01-01 11:44:07,921 | WARNING | The model training has stopped at epoch 3 due to the early stopping criterion
2023-01-01 11:58:21,870 | WARNING | The model has finished training Hippolyte_reconquest
2023-01-01 12:55:00,941 | INFO | You launched the model iteration Hippolyte_reconquest
2023-01-01 12:55:00,943 | INFO | You have chosen the model cnn Hippolyte_reconquest
2023-01-01 13:14:09,915 | INFO | Epoch [1/10], Loss: 0.921. Accuracy of the network on the test set: 59.463 %
2023-01-02 00:13:43,559 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:15:45,154 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:19:02,800 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:30:43,270 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:40:18,643 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:45:33,805 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:49:58,436 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 00:55:55,921 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 01:00:25,102 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 01:03:24,334 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 01:04:14,404 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-02 13:27:36,714 | INFO | Model parameters initialization has begun
2023-01-02 13:28:38,308 | INFO | Model parameters initialization has begun
2023-01-02 13:28:59,107 | INFO | Model parameters initialization has begun
2023-01-02 13:29:00,995 | INFO | Grid Search has started !
2023-01-03 01:17:55,039 | INFO | Model parameters initialization has begun
2023-01-03 01:21:42,123 | INFO | Model parameters initialization has begun
2023-01-03 01:22:11,321 | INFO | Model parameters initialization has begun
2023-01-03 01:24:14,010 | INFO | Model parameters initialization has begun
2023-01-03 01:24:15,691 | INFO | Grid Search has started !
2023-01-03 01:32:51,249 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:35:03,192 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:40:16,303 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:43:20,182 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:45:27,403 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:46:49,879 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:49:04,745 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:50:20,444 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 01:52:47,490 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 02:01:17,475 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 02:02:44,200 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 02:04:05,301 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 02:15:04,886 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 02:19:48,947 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 06:22:53,300 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 06:24:00,201 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 06:25:29,537 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-03 17:51:06,078 | WARNING | The Grid Search has just finished running !
2023-01-05 08:21:42,513 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 08:21:43,993 | ERROR | Trials did not complete: [train_model_eaf4a_00000, train_model_eaf4a_00001, train_model_eaf4a_00002, train_model_eaf4a_00003, train_model_eaf4a_00004, train_model_eaf4a_00005, train_model_eaf4a_00006, train_model_eaf4a_00007, train_model_eaf4a_00008, train_model_eaf4a_00009, train_model_eaf4a_00010, train_model_eaf4a_00011, train_model_eaf4a_00012, train_model_eaf4a_00013, train_model_eaf4a_00014, train_model_eaf4a_00015, train_model_eaf4a_00016, train_model_eaf4a_00017, train_model_eaf4a_00018, train_model_eaf4a_00019]
2023-01-05 08:21:43,994 | INFO | Total run time: 82759.22 seconds (82758.69 seconds for the tuning loop).
2023-01-05 08:21:43,995 | WARNING | Experiment has been interrupted, but the most recent state was saved. You can continue running this experiment by passing `resume=True` to `tune.run()`
2023-01-05 08:21:44,062 | WARNING | Couldn't read config from 16 paths
2023-01-05 08:23:30,259 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-05 08:26:05,490 | INFO | Initializing Ray automatically.For cluster usage or custom Ray initialization, call `ray.init(...)` before `tune.run`.
2023-01-05 08:29:30,525 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 08:31:26,733 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 08:31:27,019 | ERROR | Trials did not complete: [train_model_c3609_00000, train_model_c3609_00001, train_model_c3609_00002, train_model_c3609_00003]
2023-01-05 08:31:27,019 | INFO | Total run time: 86.30 seconds (85.90 seconds for the tuning loop).
2023-01-05 08:31:27,021 | WARNING | Experiment has been interrupted, but the most recent state was saved. You can continue running this experiment by passing `resume=True` to `tune.run()`
2023-01-05 11:29:06,247 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 11:34:52,575 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 11:39:49,185 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 11:41:47,828 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 11:57:50,461 | INFO | Model parameters initialization has begun
2023-01-05 11:57:52,215 | INFO | Model parameters initialization has begun
2023-01-05 11:57:53,550 | WARNING | Fitting of the model has begun, the params are :dict_items([('model_chosen', 'cnn'), ('num_classes', 2), ('batch_size', 100), ('learning_rate', 0.0001), ('num_epochs', 10), ('dropout', 0.25), ('weight_decay', 0.005), ('early_stopping', True), ('betas', '(0.9, 0.999)'), ('train_size', 0.7), ('resize', 32), ('test_image_path', 'train/0. non_cancerous/a6a2f4ed48acf6d66f7cfa1b99060325a021f0d8.tif'), ('transformers', None)])
2023-01-05 11:58:02,145 | INFO | Model parameters initialization has begun
2023-01-05 11:58:03,577 | INFO | Model parameters initialization has begun
2023-01-05 11:58:05,197 | WARNING | Fitting of the model has begun, the params are :dict_items([('model_chosen', 'cnn'), ('num_classes', 2), ('batch_size', 100), ('learning_rate', 0.0001), ('num_epochs', 10), ('dropout', 0.25), ('weight_decay', 0.005), ('early_stopping', True), ('betas', '(0.9, 0.999)'), ('train_size', 0.7), ('resize', 32), ('test_image_path', 'train/0. non_cancerous/a6a2f4ed48acf6d66f7cfa1b99060325a021f0d8.tif'), ('transformers', None)])
2023-01-05 12:00:02,550 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
2023-01-05 12:00:02,801 | ERROR | Trials did not complete: [train_model_c5697_00000, train_model_c5697_00001]
2023-01-05 12:00:02,801 | INFO | Total run time: 143.25 seconds (142.89 seconds for the tuning loop).
2023-01-05 12:00:02,801 | WARNING | Experiment has been interrupted, but the most recent state was saved. You can continue running this experiment by passing `resume=True` to `tune.run()`
2023-01-05 12:19:42,416 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:19:42,434 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff89f717661fab543ebb21d3c601000000 Worker ID: 46c75f2909376e20bb536e795dc946ab7c248ccf4606dd9eb324764d Node ID: aff07b47fa0a2385404de18fc9b3de7eda66153fa6627811de03b17f Worker IP address: 127.0.0.1 Worker port: 54282 Worker PID: 96861 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:19:42,532 | ERROR | Trial train_model_d6f28_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 89f717661fab543ebb21d3c601000000
	pid: 96861
	namespace: 8878c86a-644c-47bf-917a-6999f116d06d
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:19:42,578 | ERROR | An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 109, in _post_stop_cleanup
    ray.get(future, timeout=timeout)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 89f717661fab543ebb21d3c601000000
	pid: 96861
	namespace: 8878c86a-644c-47bf-917a-6999f116d06d
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:19:47,022 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:19:47,034 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff981c3d41853584b228531a8101000000 Worker ID: 893907cd022a8eabceb0c03e354772cd860326c48f22434fdefec907 Node ID: aff07b47fa0a2385404de18fc9b3de7eda66153fa6627811de03b17f Worker IP address: 127.0.0.1 Worker port: 54297 Worker PID: 96865 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:19:47,035 | ERROR | Trial train_model_d6f28_00001: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 981c3d41853584b228531a8101000000
	pid: 96865
	namespace: 8878c86a-644c-47bf-917a-6999f116d06d
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:22:27,249 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:22:27,263 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffa630e76f0be7715dd5c9f1e701000000 Worker ID: 763e07957e815d47b0a11ac15e8b343ade2563176e745016dbfcc273 Node ID: 5bf0799738657b48d7ee3e498fbbaa11f8393c400537f015b90d644b Worker IP address: 127.0.0.1 Worker port: 54402 Worker PID: 96992 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:22:32,198 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:22:32,207 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffd73e7c4e28321603d4b8ec2501000000 Worker ID: 2bbf8fd835ef1c42c92134f98aaa949ee47a1e38fbc9516e174e179a Node ID: 5bf0799738657b48d7ee3e498fbbaa11f8393c400537f015b90d644b Worker IP address: 127.0.0.1 Worker port: 54418 Worker PID: 96995 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:22:32,229 | ERROR | Trial train_model_38da1_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: a630e76f0be7715dd5c9f1e701000000
	pid: 96992
	namespace: 8eda103f-8238-4a44-b897-822cc0cb0650
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:22:32,250 | ERROR | An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 109, in _post_stop_cleanup
    ray.get(future, timeout=timeout)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: a630e76f0be7715dd5c9f1e701000000
	pid: 96992
	namespace: 8eda103f-8238-4a44-b897-822cc0cb0650
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:22:32,258 | ERROR | Trial train_model_38da1_00001: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: d73e7c4e28321603d4b8ec2501000000
	pid: 96995
	namespace: 8eda103f-8238-4a44-b897-822cc0cb0650
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:23:08,227 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:23:08,258 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff30df6c8cc8ac4d961c83a10501000000 Worker ID: 97739fb20120c6e978d52902cbf86e416d60f2884faf287e7b443edd Node ID: 1763d43c28140dd38d534cee12ab852d148db687af29cfb66fc457bd Worker IP address: 127.0.0.1 Worker port: 54515 Worker PID: 97093 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:23:08,348 | ERROR | Trial train_model_517d1_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 30df6c8cc8ac4d961c83a10501000000
	pid: 97093
	namespace: f9bde413-5a85-4adb-8c2a-d22d42a58a16
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:23:08,365 | ERROR | An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 109, in _post_stop_cleanup
    ray.get(future, timeout=timeout)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 30df6c8cc8ac4d961c83a10501000000
	pid: 97093
	namespace: f9bde413-5a85-4adb-8c2a-d22d42a58a16
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:23:13,195 | WARNING | Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:23:13,208 | WARNING | A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffeb9dfbff40d53856c8d1fa2a01000000 Worker ID: 57adf19af6431f8c180c9c6cddb2790364d3005ac4e57511019e430c Node ID: 1763d43c28140dd38d534cee12ab852d148db687af29cfb66fc457bd Worker IP address: 127.0.0.1 Worker port: 54530 Worker PID: 97104 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.
2023-01-05 12:23:13,211 | ERROR | Trial train_model_517d1_00001: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: eb9dfbff40d53856c8d1fa2a01000000
	pid: 97104
	namespace: f9bde413-5a85-4adb-8c2a-d22d42a58a16
	ip: 127.0.0.1
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 823, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 875, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1135, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1045, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 782, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 945, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 575, in ray._raylet.store_task_errors
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 586, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/Users/hippodouche/opt/anaconda3/envs/hispatologic_cancer_detection_environment/lib/python3.10/site-packages/ray/_private/function_manager.py", line 625, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'github'

An unexpected internal error occurred while the worker was executing a task.

2023-01-05 12:26:22,235 | WARNING | Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
